# Generated by Django 5.0.6 on 2024-06-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialForm',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('roll', models.PositiveIntegerField()),
                ('email_field', models.EmailField(max_length=254)),
                ('exam_day', models.DateField()),
                ('exam_time', models.DateTimeField()),
                ('exam_duartion', models.DurationField()),
                ('expected_exam_finish_time', models.TimeField()),
                ('expected_average_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('big_auto_field', models.BigAutoField(primary_key=True, serialize=False)),
                ('big_integer_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('message_to_us', models.TextField()),
            ],
        ),
    ]
