# Generated by Django 5.0.6 on 2024-06-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialform',
            old_name='exam_duartion',
            new_name='exam_duration',
        ),
    ]
